name: CI/CD Pipeline for Mule API Deployment

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Cache Maven dependencies
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build the application
      run: mvn clean install

    - name: Deploy to CloudHub
      env:
        MULE_USERNAME: ${{ secrets.ANYPOINT_USERNAME }}
        MULE_PASSWORD: ${{ secrets.ANYPOINT_PASSWORD }}
        APP_NAME: 's-test-rjaencobos'
        ENVIRONMENT: 'prod'
        TARGET_NAME: 'prod-target'
        MULE_VERSION: '4.9.2'
        PUBLIC_URL: 'https://your-public-url'
      run: mvn clean deploy
